#============================================
# Density Analysis
Density:
  run: False
  data:
    #- name: HRDE1_WT
    - name: HRDE1_CSR1
  columns:
    - ALL
    - UTR5
    - CDS
    - UTR3
  reference: metadata/analyze/mRNA_WS275_3region.csv
  csv_path: metadata/analyze/density/
#============================================
# Metagene Analysis
Metagene:
  run: False
  data:
    #- name: HRDE1_WT
    - name: HRDE1_CSR1
  reference: metadata/analyze/mRNA_WS275_metagene.csv
  csv_path: metadata/analyze/metagene/
#============================================
# Head/Tail Analysis
Boundary:
  run: False
  data:
    - name: HRDE1_WT
    #- name: HRDE1_CSR1
  columns: 
    - head
    - tail
  limit:
    - [0,100]
    - [-100,0]
  reference: metadata/analyze/mRNA_WS275_boundary.csv
  csv_path: metadata/analyze/boundary/
#============================================
# Start/Stop Codon Analysis
Codon:
  run: False
  data:
    - name: HRDE1_WT
    #- name: HRDE1_CSR1
  columns: 
    - start codon
    - stop codon
  limit:
    - [-100,100]
    - [-100,100]
  reference: metadata/analyze/mRNA_WS275_boundary.csv
  csv_path: metadata/analyze/codon/
#============================================
# Fold Change Analysis
Fold_Change:
  run: False
  data:
    - name: HRDE1_WT
    - name: HRDE1_CSR1
  columns:
    - ALL
    - UTR5
    - CDS
    - UTR3
  reference: metadata/analyze/mRNA_WS275_3region.csv
  csv_path: metadata/analyze/fold-change/
#============================================
# Scatter Analysis
Scatter:
  run: False
  data:
    - name: HRDE1_WT
    - name: HRDE1_CSR1
  columns:
    - ALL
    - UTR5
    - CDS
    - UTR3
  reference: metadata/analyze/mRNA_WS275_3region.csv
  csv_path: metadata/analyze/scatter/
#============================================
# User Defined "Region Analysis"
Region:
  run: False
  data:
  columns:
  reference:
  csv_path:
#============================================
# User Defined "Position Analysis"
Position:
  run: False
  data:
  columns:
  limit:
  reference:
  csv_path:
#============================================