# metadata after preprocess
data:
  - name: HRDE1_WT
    path: metadata/preprocess/HRDE-1_WT_rep1.csv
    replicate: 1
  
  - name: HRDE1_CSR1
    path: metadata/preprocess/HRDE-1_csr1_KO_rep1.csv
    replicate: 1

# metadata after analyze
metadata:
  - name: HRDE1_WT
    path: 
  
  - name:
    path: