#============================================
General:
  # Determine the backgroud style of figure.
  # Check the link below for more details.
  # https://seaborn.pydata.org/archive/0.9/tutorial/aesthetics.html#aesthetics-tutorial
  # eg. darkgrid, whitegrid, dark, white, ticks
  style: darkgrid

  # Determine the color palette of figure.
  # Check the link below for more details.
  # https://seaborn.pydata.org/archive/0.9/tutorial/color_palettes.html#palette-tutorial
  # eg. coolwarm, deep, hls, Greys
  color: coolwarm

  # Determine the format of figure.
  # eg. png, svg
  fig_format: png

#============================================
Box_Plot:
  # Determine the color palette of figure.
  color: coolwarm

  # Add mean and median to x-ticks.
  show_detail: True

  # Determine the scale of y-axis.
  # eg. normal, log2, log10
  scale: log2

  # If it's "multi-data to multi-filter", determine which field should be set as x-axis.
  # eg. data, filter
  x_axis: data

  # Determine which testing method to use.
  # eg. None, U-test, T-test
  test: U-test

  # Determine the representation method of the test.
  # Check the link below for more details.
  # https://github.com/webermarcolivier/statannot
  # eg. simple, full, star
  test_format: simple

#============================================
Line_Plot:
  # Determine the color palette of figure.
  color: deep

  # If it's "multi-data to multi-filter", determine which field should be set as hue.
  # eg. data, filter
  hue: data

  # Determine the xlabel of figure.
  # eg. region(%), nt
  xlabel: None

  # Determine the positions of vertical line in a format of list.
  # eg. [0,100,...]
  vertical_line: None

#============================================