data:
  - name: WAGO1 IP
    path: metadata/preprocess/WAGOIP_WT.csv
    replicate: 1
    normalization: 10^6 / miRNA total read count
    norm_facor: 
    species: C.elegans
    type: wild-type
    discription: GSM3578001; WT_CRISPR_WAGO-1-FLAG_IP_sRNA-seq; Caenorhabditis elegans; OTHER (SRR8482951)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8482951
  
  - name: WAGO1 IP PRG1 MUT
    path: metadata/preprocess/WAGOIP_PRG1_MUT.csv
    replicate: 1
    normalization: 10^6 / miRNA total read count
    norm_facor: 
    species: C.elegans
    type: mutant
    discription: GSM3577999; piwi_CRISPR_WAGO-1-FLAG_IP_sRNA-seq; Caenorhabditis elegans; OTHER (SRR8482949)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8482949

  - name: HRDE1_IP_WT1
    path: metadata/preprocess/HRDE-1_WT_rep1.csv
    replicate: 1
    normalization: 10^6 / miRNA total read count
    norm_facor: 2.96854
    species: C.elegans
    type: wild-type
    discription: GSM4694798; GFP_HRDE-1_WT_lateL4_IP_rep1_sRNA-seq; Caenorhabditis elegans; RIP-Seq (SRR12318140)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12318140

  - name: HRDE1_IP_CSR1_KO1
    path: metadata/preprocess/HRDE-1_csr1_KO_rep1.csv
    replicate: 1
    normalization: 10^6 / miRNA total read count
    norm_facor: 6.70997
    species: C.elegans
    type: mutant
    discription: GSM4694802; GFP_HRDE-1_csr-1_KO_lateL4_IP_rep1_sRNA-seq; Caenorhabditis elegans; RIP-Seq (SRR12318144)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12318144

  - name: HRDE1_IP_WT2
    path: metadata/preprocess/HRDE-1_WT_rep2.csv
    replicate: 2
    normalization: 10^6 / miRNA total read count
    norm_facor: 
    species: C.elegans
    type: wild-type
    discription: GSM4694799; GFP_HRDE-1_WT_lateL4_IP_rep2_sRNA-seq; Caenorhabditis elegans; RIP-Seq (SRR12318141)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12318141

  - name: HRDE1_IP_CSR1_KO2
    path: metadata/preprocess/HRDE-1_csr1_KO_rep1.csv
    replicate: 2
    normalization: 10^6 / miRNA total read count
    norm_facor: 
    species: C.elegans
    type: mutant
    discription: GSM4694803; GFP_HRDE-1_csr-1_KO_lateL4_IP_rep2_sRNA-seq; Caenorhabditis elegans; RIP-Seq (SRR12318145)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12318145

  - name: CSR1_IP_WT1
    path: metadata/preprocess/HRDE-1_WT_rep2.csv
    replicate: 1
    normalization: 10^6 / miRNA total read count
    norm_facor: 
    species: C.elegans
    type: wild-type
    discription: GSM4694790; FLAG_CSR-1_WT_lateL4_IP_rep1_sRNA-seq; Caenorhabditis elegans; RIP-Seq (SRR12318132)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12318132
  
  - name: CSR1_IP_Slicer_KO1
    path: metadata/preprocess/HRDE-1_csr1_KO_rep1.csv
    replicate: 1
    normalization: 10^6 / miRNA total read count
    norm_facor: 
    species: C.elegans
    type: mutant
    discription: GSM4694792; FLAG_CSR-1_ADH_lateL4_IP_rep1_sRNA-seq; Caenorhabditis elegans; RIP-Seq (SRR12318134)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12318134

  - name: CSR1_IP_WT2
    path: metadata/preprocess/HRDE-1_WT_rep2.csv
    replicate: 2
    normalization: 10^6 / miRNA total read count
    norm_facor: 
    species: C.elegans
    type: wild-type
    discription: GSM4694791; FLAG_CSR-1_WT_lateL4_IP_rep2_sRNA-seq; Caenorhabditis elegans; RIP-Seq (SRR12318133)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12318133
  
  - name: CSR1_IP_Slicer_KO2
    path: metadata/preprocess/HRDE-1_csr1_KO_rep1.csv
    replicate: 2
    normalization: 10^6 / miRNA total read count
    norm_facor: 
    species: C.elegans
    type: mutant
    discription: GSM4694793; FLAG_CSR-1_ADH_lateL4_IP_rep2_sRNA-seq; Caenorhabditis elegans; RIP-Seq (SRR12318135)
    url: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12318135

filter:
  - name: all mRNAs
    path: toolkit/sRNAanalyzer/filter/all_mRNAs
  - name: WAGO-1_target
    path: toolkit/sRNAanalyzer/filter/WAGO-1_target
  - name: CSR-1_target
    path: toolkit/sRNAanalyzer/filter/CSR-1_target
  - name: Desilenced_wago
    path: toolkit/sRNAanalyzer/filter/Desilenced_wago
  - name: Germline_target
    path: toolkit/sRNAanalyzer/filter/Germline_target
  - name: Germline_enriched_target
    path: toolkit/sRNAanalyzer/filter/Germline_enriched_target
  - name: Missilenced_csr
    path: toolkit/sRNAanalyzer/filter/Missilenced_csr
  - name: Soma_target
    path: toolkit/sRNAanalyzer/filter/Soma_target
  - name: bottom_10_TE_csr
    path: toolkit/sRNAanalyzer/filter/bottom_10_TE_csr
  - name: bottom_10_TE_csr(transcript)
    path: toolkit/sRNAanalyzer/filter/bottom_10_TE_csr(transcript)
  - name: bottom_10_TE_wago
    path: toolkit/sRNAanalyzer/filter/bottom_10_TE_wago
  - name: bottom_10_TE_wago(transcript)
    path: toolkit/sRNAanalyzer/filter/bottom_10_TE_wago(transcript)
  - name: bottom_10_ribo_RPM_csr
    path: toolkit/sRNAanalyzer/filter/bottom_10_ribo_RPM_csr
  - name: bottom_10_ribo_RPM_wago
    path: toolkit/sRNAanalyzer/filter/bottom_10_ribo_RPM_wago
  - name: bottom_10_ribo_csr
    path: toolkit/sRNAanalyzer/filter/bottom_10_ribo_csr
  - name: bottom_10_ribo_csr(transcript)
    path: toolkit/sRNAanalyzer/filter/bottom_10_ribo_csr(transcript)
  - name: bottom_10_ribo_wago
    path: toolkit/sRNAanalyzer/filter/bottom_10_ribo_wago
  - name: bottom_10_ribo_wago(transcript)
    path: toolkit/sRNAanalyzer/filter/bottom_10_ribo_wago(transcript)
  - name: csr1_last_25_enriched
    path: toolkit/sRNAanalyzer/filter/csr1_last_25_enriched
  - name: csr1_not_enriched
    path: toolkit/sRNAanalyzer/filter/csr1_not_enriched
  - name: csr1_not_enriched_10_165
    path: toolkit/sRNAanalyzer/filter/csr1_not_enriched_10_165
  - name: csr1_not_enriched_25_30
    path: toolkit/sRNAanalyzer/filter/csr1_not_enriched_25_30
  - name: csr1_rpm_10
    path: toolkit/sRNAanalyzer/filter/csr1_rpm_10
  - name: csr1_rpm_5
    path: toolkit/sRNAanalyzer/filter/csr1_rpm_5
  - name: csr1_rpm_90
    path: toolkit/sRNAanalyzer/filter/csr1_rpm_90
  - name: csr1_rpm_95
    path: toolkit/sRNAanalyzer/filter/csr1_rpm_95
  - name: favored_3utr
    path: toolkit/sRNAanalyzer/filter/favored_3utr
  - name: glh_wago
    path: toolkit/sRNAanalyzer/filter/glh_wago
  - name: intron_0_202301
    path: toolkit/sRNAanalyzer/filter/intron_0_202301
  - name: intron_0_CSR_202301
    path: toolkit/sRNAanalyzer/filter/intron_0_CSR_202301
  - name: intron_0_WAGO_202301
    path: toolkit/sRNAanalyzer/filter/intron_0_WAGO_202301
  - name: intron_1-3_202301
    path: toolkit/sRNAanalyzer/filter/intron_1-3_202301
  - name: intron_1-3_CSR_202301
    path: toolkit/sRNAanalyzer/filter/intron_1-3_CSR_202301
  - name: intron_1-3_WAGO_202301
    path: toolkit/sRNAanalyzer/filter/intron_1-3_WAGO_202301
  - name: intron_4-7_202301
    path: toolkit/sRNAanalyzer/filter/intron_4-7_202301
  - name: intron_4-7_CSR_202301
    path: toolkit/sRNAanalyzer/filter/intron_4-7_CSR_202301
  - name: intron_4-7_WAGO_202301
    path: toolkit/sRNAanalyzer/filter/intron_4-7_WAGO_202301
  - name: intron_count_high_csr(8-over30)
    path: toolkit/sRNAanalyzer/filter/intron_count_high_csr(8-over30)
  - name: intron_count_high_wago(8-over30)
    path: toolkit/sRNAanalyzer/filter/intron_count_high_wago(8-over30)
  - name: intron_count_low_csr(1-3)
    path: toolkit/sRNAanalyzer/filter/intron_count_low_csr(1-3)
  - name: intron_count_low_wago(1-3)
    path: toolkit/sRNAanalyzer/filter/intron_count_low_wago(1-3)
  - name: intron_count_middle_csr(4-7)
    path: toolkit/sRNAanalyzer/filter/intron_count_middle_csr(4-7)
  - name: intron_count_middle_wago(4-7)
    path: toolkit/sRNAanalyzer/filter/intron_count_middle_wago(4-7)
  - name: intron_density_csr_high
    path: toolkit/sRNAanalyzer/filter/intron_density_csr_high
  - name: intron_density_csr_low
    path: toolkit/sRNAanalyzer/filter/intron_density_csr_low
  - name: intron_density_csr_middle
    path: toolkit/sRNAanalyzer/filter/intron_density_csr_middle
  - name: intron_density_csr_zero
    path: toolkit/sRNAanalyzer/filter/intron_density_csr_zero
  - name: intron_density_wago_high
    path: toolkit/sRNAanalyzer/filter/intron_density_wago_high
  - name: intron_density_wago_low
    path: toolkit/sRNAanalyzer/filter/intron_density_wago_low
  - name: intron_density_wago_middle
    path: toolkit/sRNAanalyzer/filter/intron_density_wago_middle
  - name: intron_density_wago_zero
    path: toolkit/sRNAanalyzer/filter/intron_density_wago_zero
  - name: intron_in_3UTR
    path: toolkit/sRNAanalyzer/filter/intron_in_3UTR
  - name: intron_in_3UTR_csr
    path: toolkit/sRNAanalyzer/filter/intron_in_3UTR_csr
  - name: intron_in_3UTR_wago
    path: toolkit/sRNAanalyzer/filter/intron_in_3UTR_wago
  - name: intron_in_5UTR
    path: toolkit/sRNAanalyzer/filter/intron_in_5UTR
  - name: intron_in_5UTR_csr
    path: toolkit/sRNAanalyzer/filter/intron_in_5UTR_csr
  - name: intron_in_5UTR_wago
    path: toolkit/sRNAanalyzer/filter/intron_in_5UTR_wago
  - name: intron_over7_202301
    path: toolkit/sRNAanalyzer/filter/intron_over7_202301
  - name: intron_over7_CSR_202301
    path: toolkit/sRNAanalyzer/filter/intron_over7_CSR_202301
  - name: intron_over7_WAGO_202301
    path: toolkit/sRNAanalyzer/filter/intron_over7_WAGO_202301
  - name: intron_pos_csr_high
    path: toolkit/sRNAanalyzer/filter/intron_pos_csr_high
  - name: intron_pos_csr_low
    path: toolkit/sRNAanalyzer/filter/intron_pos_csr_low
  - name: intron_pos_csr_middle
    path: toolkit/sRNAanalyzer/filter/intron_pos_csr_middle
  - name: intron_pos_wago_high
    path: toolkit/sRNAanalyzer/filter/intron_pos_wago_high
  - name: intron_pos_wago_low
    path: toolkit/sRNAanalyzer/filter/intron_pos_wago_low
  - name: intron_pos_wago_middle
    path: toolkit/sRNAanalyzer/filter/intron_pos_wago_middle
  - name: meg_wago
    path: toolkit/sRNAanalyzer/filter/meg_wago
  - name: no_intron
    path: toolkit/sRNAanalyzer/filter/no_intron
  - name: no_intron_csr
    path: toolkit/sRNAanalyzer/filter/no_intron_csr
  - name: no_intron_wago
    path: toolkit/sRNAanalyzer/filter/no_intron_wago
  - name: top25_closest_first_intron
    path: toolkit/sRNAanalyzer/filter/top25_closest_first_intron
  - name: top25_closest_first_intron_csr
    path: toolkit/sRNAanalyzer/filter/top25_closest_first_intron_csr
  - name: top25_closest_first_intron_wago
    path: toolkit/sRNAanalyzer/filter/top25_closest_first_intron_wago
  - name: top25_furthest_first_intron
    path: toolkit/sRNAanalyzer/filter/top25_furthest_first_intron
  - name: top25_furthest_first_intron_csr
    path: toolkit/sRNAanalyzer/filter/top25_furthest_first_intron_csr
  - name: top25_furthest_first_intron_wago
    path: toolkit/sRNAanalyzer/filter/top25_furthest_first_intron_wago
  - name: top25_least_introns
    path: toolkit/sRNAanalyzer/filter/top25_least_introns
  - name: top25_least_introns_csr
    path: toolkit/sRNAanalyzer/filter/top25_least_introns_csr
  - name: top25_least_introns_wago
    path: toolkit/sRNAanalyzer/filter/top25_least_introns_wago
  - name: top25_most_introns
    path: toolkit/sRNAanalyzer/filter/top25_most_introns
  - name: top25_most_introns_csr
    path: toolkit/sRNAanalyzer/filter/top25_most_introns_csr
  - name: top25_most_introns_wago
    path: toolkit/sRNAanalyzer/filter/top25_most_introns_wago
  - name: top_10_TE_csr
    path: toolkit/sRNAanalyzer/filter/top_10_TE_csr
  - name: top_10_TE_csr(transcript)
    path: toolkit/sRNAanalyzer/filter/top_10_TE_csr(transcript)
  - name: top_10_TE_wago
    path: toolkit/sRNAanalyzer/filter/top_10_TE_wago
  - name: top_10_TE_wago(transcript)
    path: toolkit/sRNAanalyzer/filter/top_10_TE_wago(transcript)
  - name: top_10_ribo_RPM_csr
    path: toolkit/sRNAanalyzer/filter/top_10_ribo_RPM_csr
  - name: top_10_ribo_RPM_wago
    path: toolkit/sRNAanalyzer/filter/top_10_ribo_RPM_wago
  - name: top_10_ribo_csr
    path: toolkit/sRNAanalyzer/filter/top_10_ribo_csr
  - name: top_10_ribo_csr(transcript)
    path: toolkit/sRNAanalyzer/filter/top_10_ribo_csr(transcript)
  - name: top_10_ribo_wago
    path: toolkit/sRNAanalyzer/filter/top_10_ribo_wago
  - name: top_10_ribo_wago(transcript)
    path: toolkit/sRNAanalyzer/filter/top_10_ribo_wago(transcript)
  - name: wago_2fold_enriched_csr_depleted
    path: toolkit/sRNAanalyzer/filter/wago_2fold_enriched_csr_depleted